#!/bin/sh

set -e

npm install
export PATH="node_modules/.bin:node_modules/hubot/node_modules/.bin:$PATH"

# Slack Settings
export HUBOT_SLACK_TOKEN=hogehoge
export PORT=9999

#exec node_modules/.bin/hubot --name "spartan-duck" "$@"
forever start -w -c coffee node_modules/.bin/hubot -a slack

 #./bin/hubot --adapter slack
